### ISSUE TITLE
Important for people taking this challenge

### ISSUE THREAD

**Issue by juangl** [Superformula/test-web-stack#61]
For people taking this challenge, I'm sharing my experience for you to be aware:

I took this challenge for the frontend role. My PR was sent right before Christmas: https://github.com/Superformula/test-web-stack/pull/55. I spent 16 hours working on it since I wanted to build the backend as well for learning purposes and to get a higher score. 

I received an email confirming that I was moving to the last stage: an interview with two guys. After this interview, I received a generic email saying they were "grateful for the time and energy" but they won't be moving forward, I replied twice asking for a little more feedback since I spent a significant amount of time in the entire process and I really want to know what went wrong but they never replied.

For the Superformula team, I respectfully encourage you to be mindful about your process being on average more energy-consuming than the rest in the industry and to be fair, the least your applicants deserve is that you don't completely waste their time.

**Comment by afaq-sf** [comment]
Hi @juangl 

Appreciate the feedback here. I looked back through the timeline of your application and what you wrote here is fair. You took the code challenge and we didn't get back to you on your emails for more thorough feedback. Our executive team wanted to response here but I wanted to reach out first to make the situation right, since I am the Engineering Hiring Manager for this role. It is my responsibility to get Engineers in late stages feedback. I'm sorry that was a miss here, Juan. I'm an engineer myself and this isn't the experience I want associated with us or me.

I appreciate the time you took especially around Christmas for the code challenge. I know the 2 Engineers who reviewed it and left questions also appreciated your code and answers in the PR. I think the disconnect here is that I dropped the ball in getting back to you on specific feedback in Dec in the wrap-up email.

Anyone who takes our code challenge deserves a non-generic response, regardless of whether they ask, just out of respect for their time - we can agree on that. That's usually our approach through the PR comments, follow-up interview, and wrap-up email. It seems I missed the mark on that approach here.

Let me collate the feedback from the reviewers and interviewers and share out with you today. In the meantime, please feel free to add more thoughts here in this thread, we're a small shop and always open to direct feedback.

Appreciate your straightforward and professional message here, man. Sincerely. I feel like you're helping us out here.

**Comment by juangl** [comment]
hey @afaq-sf

Thanks for your quick response and I already received your email with your feedback, it's sincerely appreciated!

Ultimately, as someone who has been on both sides of the table, my end goal is to have a better recruitment process for both, companies and engineers. Recruiting is tough and a perfect process doesn't exist but here are my thoughts from what I've learned recently from other processes that I've gone through recently:

- Be transparent about what the full process is like, what are metrics you measure on each stage, and how you evaluate them
- Ideally, metrics should be quantifiable, even if you are evaluating non-technical skills
- feedback is important and since usually you are evaluated in contrast with other candidates, it useful to know what other candidate did better than you
